site_name: Cloud Optimized Geospatial Data Access 
site_url: https://nrcan.github.io/cloud-optimized-geospatial/
repo_url: https://github.com/NRCan/cloud-optimized-geospatial
repo_name: NRCan/cloud-optimized-geospatial
copyright: <a href="https://open.canada.ca/en/open-government-licence-canada"> Open Government Licence - Canada</a>

site_dir: public

# docs_dir: .

theme:
  # name: readthedocs
  name: material
  language: en
  features:
    - content.code.copy
    - search.highlight
    - navigation.path # Ne semble pas fonctionner...
    - navigation.top
    - navigation.footer
    - content.tooltips
    # - content.action.view # To see the source page, we don't want that
  #   - navigation.tabs # Ne fonctionnne pas...
    # - navigation.indexes
    # - navigation.footer

# extra: 
#   social: # Ne marche pas
#     - icon: fontawesome/brands/github
#       link: https://github.com/NRCan/cloud-optimized-geospatial

plugins:
  # - same-dir
  - search
  - mkdocstrings :
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_options
        # https://mkdocstrings.github.io/griffe/docstrings/#examples_1
        python:
          options:
            docstring_style: numpy
            merge_init_into_class: True
            show_if_no_docstring: true
            # docstring_section_style: table
            # show_docstring_modules : False
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: NRCan/cloud-optimized-geospatial
      branch: main
      exclude_committers: 
        - web-flow
      # token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français
      docs_structure: folder

markdown_extensions:
  - pymdownx.snippets # THIS IS SICK!!!! https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences # For the colors in the python codeblocks
  # - pymdownx.details
  - admonition
  - pymdownx.emoji
  - abbr
  - toc:
      permalink: true
  # - footnotes

nav:
  - Home : index.md
  # - readme : README.md
  - How-to Guides : 
    - STAC API : pystac-client.md
  # - Interact with COGs
    - COG : example-cogs.md
    - Additionnal libraires : pystac-into-xarray.md
    # - Other : docs/index.md
  - External References : reference.md
  - Additional Information :
    - Known Bugs : reorder-transform-example.md
      # - FAQ
